//
//  Created by Jerel Walters on 6/30/26.
//  Copyright © 2026 Jerel Walters. All rights reserved.
//

import AuthorizationModule

typealias SessionUser = AuthorizationModule.SessionUser
typealias SignInRequest = AuthorizationModule.SignInRequest
typealias SignUpRequest = AuthorizationModule.SignUpRequest
typealias BusinessProfileDraft = AuthorizationModule.BusinessProfileDraft
typealias BusinessProfileValidationError = AuthorizationModule.BusinessProfileValidationError
typealias BusinessProfileValidationReason = AuthorizationModule.BusinessProfileValidationReason
typealias BusinessProfileField = AuthorizationModule.BusinessProfileField

typealias AuthSession = AuthorizationModule.AuthSession
typealias AuthSessionStoring = AuthorizationModule.AuthSessionStoring
typealias BusinessProfileStoring = AuthorizationModule.BusinessProfileStoring
typealias AuthSessionRefreshing = AuthorizationModule.AuthSessionRefreshing
typealias NoOpAuthSessionRefresher = AuthorizationModule.NoOpAuthSessionRefresher
typealias AccountScopedDataClearing = AuthorizationModule.AccountScopedDataClearing

typealias AuthRepository = AuthorizationModule.AuthRepository
typealias AuthStatus = AuthorizationModule.AuthStatus
typealias AuthRepositoryError = AuthorizationModule.AuthRepositoryError
typealias AuthService = AuthorizationModule.AuthService
typealias AuthenticationActionResult = AuthorizationModule.AuthenticationActionResult
typealias AuthenticatedUserActionResult = AuthorizationModule.AuthenticatedUserActionResult
typealias BusinessProfileActionResult = AuthorizationModule.BusinessProfileActionResult
