-- P0-BE-06: Idempotent sync contracts for local-first load writes.
--
-- The iOS outbox sends client UUIDs plus an idempotency key. The database
-- stores one server response per key so retries reconcile to the same result.

create table public.sync_operations (
  id uuid primary key,
  user_id uuid not null references public.business_profiles(user_id) on delete cascade,
  idempotency_key text not null,
  operation_type text not null,
  target_table text not null,
  target_id uuid not null,
  request_hash text not null,
  result_status text not null,
  response jsonb not null,
  error_code text,
  server_received_at timestamp with time zone not null default now(),
  last_replayed_at timestamp with time zone,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now(),

  constraint sync_operations_user_id_id_unique unique (user_id, id),
  constraint sync_operations_idempotency_key_unique unique (user_id, idempotency_key),
  constraint sync_operations_idempotency_key_required
    check (char_length(btrim(idempotency_key)) > 0 and char_length(btrim(idempotency_key)) <= 160),
  constraint sync_operations_type_required
    check (char_length(btrim(operation_type)) > 0 and char_length(btrim(operation_type)) <= 80),
  constraint sync_operations_target_table_allowed
    check (target_table in ('loads')),
  constraint sync_operations_request_hash_format
    check (request_hash ~ '^[0-9a-f]{32}$'),
  constraint sync_operations_result_status_allowed
    check (result_status in ('applied', 'rejected')),
  constraint sync_operations_error_code_shape
    check (
      (result_status = 'applied' and error_code is null)
      or (result_status = 'rejected' and char_length(btrim(coalesce(error_code, ''))) > 0)
    )
);

comment on table public.sync_operations is
  'Server replay ledger for idempotent mobile sync operations.';
comment on column public.sync_operations.id is
  'Client-generated outbox operation UUID.';
comment on column public.sync_operations.idempotency_key is
  'Stable retry key generated by the client for one logical operation.';
comment on column public.sync_operations.response is
  'Stable response returned for initial success/rejection and every retry.';

create trigger set_sync_operations_updated_at
before update on public.sync_operations
for each row
execute function app_private.set_updated_at();

create index sync_operations_user_id_idx on public.sync_operations (user_id);
create index sync_operations_target_idx on public.sync_operations (user_id, target_table, target_id);
create index sync_operations_server_received_at_idx on public.sync_operations (server_received_at desc);

revoke all on table public.sync_operations from anon, authenticated, service_role;
grant select on table public.sync_operations to authenticated;
grant select, insert, update, delete on table public.sync_operations to service_role;

alter table public.sync_operations enable row level security;

create policy "Users can read their own sync operations"
on public.sync_operations
for select
to authenticated
using ((select auth.uid()) = user_id);

create or replace function app_private.is_load_status_transition_allowed(
  current_status text,
  next_status text
)
returns boolean
language sql
immutable
security invoker
set search_path = ''
as $$
  select case current_status
    when 'evaluating' then next_status in ('evaluating', 'accepted', 'cancelled')
    when 'accepted' then next_status in ('accepted', 'en_route_to_pickup', 'cancelled')
    when 'en_route_to_pickup' then next_status in ('en_route_to_pickup', 'at_pickup', 'cancelled')
    when 'at_pickup' then next_status in ('at_pickup', 'in_transit', 'cancelled')
    when 'in_transit' then next_status in ('in_transit', 'at_delivery', 'cancelled', 'disputed')
    when 'at_delivery' then next_status in ('at_delivery', 'delivered', 'disputed')
    when 'delivered' then next_status in ('delivered', 'invoiced', 'disputed')
    when 'invoiced' then next_status in ('invoiced', 'paid', 'disputed')
    when 'paid' then next_status in ('paid', 'disputed')
    when 'cancelled' then next_status = 'cancelled'
    when 'disputed' then next_status in ('disputed', 'invoiced', 'paid', 'cancelled')
    else false
  end;
$$;

revoke execute on function app_private.is_load_status_transition_allowed(text, text) from public, anon, authenticated;

create or replace function public.apply_load_sync_operation(
  p_operation_id uuid,
  p_idempotency_key text,
  p_load jsonb,
  p_expected_server_updated_at timestamp with time zone default null
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_user_id uuid := auth.uid();
  v_target_id uuid;
  v_customer_id uuid;
  v_vehicle_id uuid;
  v_reference_number text;
  v_status text;
  v_line_haul_rate numeric(12, 2);
  v_fuel_surcharge numeric(12, 2);
  v_accessorial_revenue numeric(12, 2);
  v_loaded_miles numeric(10, 2);
  v_deadhead_miles numeric(10, 2);
  v_estimated_tolls numeric(12, 2);
  v_gross_revenue numeric(12, 2);
  v_total_operating_cost numeric(12, 2);
  v_estimated_profit numeric(12, 2);
  v_profit_margin numeric(7, 4);
  v_revenue_per_loaded_mile numeric(12, 2);
  v_revenue_per_total_mile numeric(12, 2);
  v_accepted_at timestamp with time zone;
  v_delivered_at timestamp with time zone;
  v_request_hash text;
  v_existing_operation public.sync_operations%rowtype;
  v_existing_load public.loads%rowtype;
  v_saved_load public.loads%rowtype;
  v_response jsonb;
  v_financial_changed boolean;
begin
  if v_user_id is null then
    raise exception 'apply_load_sync_operation requires an authenticated user'
      using errcode = '42501';
  end if;

  if p_operation_id is null then
    raise exception 'operation_id is required'
      using errcode = '23502';
  end if;

  if p_load is null or jsonb_typeof(p_load) <> 'object' then
    raise exception 'load payload must be a JSON object'
      using errcode = '22023';
  end if;

  v_target_id := nullif(p_load ->> 'id', '')::uuid;
  v_customer_id := nullif(p_load ->> 'customer_id', '')::uuid;
  v_vehicle_id := nullif(p_load ->> 'vehicle_id', '')::uuid;
  v_reference_number := p_load ->> 'reference_number';
  v_status := p_load ->> 'status';
  v_line_haul_rate := (p_load ->> 'line_haul_rate')::numeric;
  v_fuel_surcharge := coalesce((p_load ->> 'fuel_surcharge')::numeric, 0);
  v_accessorial_revenue := coalesce((p_load ->> 'accessorial_revenue')::numeric, 0);
  v_loaded_miles := (p_load ->> 'loaded_miles')::numeric;
  v_deadhead_miles := coalesce((p_load ->> 'deadhead_miles')::numeric, 0);
  v_estimated_tolls := coalesce((p_load ->> 'estimated_tolls')::numeric, 0);
  v_gross_revenue := (p_load ->> 'gross_revenue')::numeric;
  v_total_operating_cost := (p_load ->> 'total_operating_cost')::numeric;
  v_estimated_profit := (p_load ->> 'estimated_profit')::numeric;
  v_profit_margin := (p_load ->> 'profit_margin')::numeric;
  v_revenue_per_loaded_mile := (p_load ->> 'revenue_per_loaded_mile')::numeric;
  v_revenue_per_total_mile := (p_load ->> 'revenue_per_total_mile')::numeric;
  v_accepted_at := (p_load ->> 'accepted_at')::timestamp with time zone;
  v_delivered_at := (p_load ->> 'delivered_at')::timestamp with time zone;

  v_request_hash := pg_catalog.md5(
    jsonb_build_object(
      'operation_id', p_operation_id,
      'idempotency_key', p_idempotency_key,
      'operation_type', 'load.upsert',
      'load', p_load,
      'expected_server_updated_at', p_expected_server_updated_at
    )::text
  );

  select *
  into v_existing_operation
  from public.sync_operations
  where user_id = v_user_id
    and idempotency_key = p_idempotency_key
  for update;

  if found then
    if v_existing_operation.request_hash <> v_request_hash then
      raise exception 'idempotency key already used for a different payload'
        using errcode = '22023';
    end if;

    update public.sync_operations
    set last_replayed_at = now()
    where user_id = v_user_id
      and id = v_existing_operation.id;

    return v_existing_operation.response;
  end if;

  if p_idempotency_key is null
     or char_length(btrim(p_idempotency_key)) = 0
     or char_length(btrim(p_idempotency_key)) > 160 then
    raise exception 'idempotency_key is required and must be at most 160 characters'
      using errcode = '22023';
  end if;

  if v_target_id is null
     or v_customer_id is null
     or char_length(btrim(coalesce(v_reference_number, ''))) = 0
     or v_status is null
     or v_line_haul_rate is null
     or v_loaded_miles is null then
    raise exception 'load payload is missing required fields'
      using errcode = '23502';
  end if;

  select *
  into v_existing_load
  from public.loads
  where user_id = v_user_id
    and id = v_target_id
  for update;

  if found then
    if p_expected_server_updated_at is not null
       and v_existing_load.updated_at <> p_expected_server_updated_at then
      v_response := jsonb_build_object(
        'operation_id', p_operation_id,
        'idempotency_key', p_idempotency_key,
        'operation_type', 'load.upsert',
        'target_table', 'loads',
        'target_id', v_target_id,
        'result', 'rejected',
        'error_code', 'stale_server_record',
        'reconciliation', jsonb_build_object(
          'server_created_at', v_existing_load.created_at,
          'server_updated_at', v_existing_load.updated_at
        )
      );

      insert into public.sync_operations (
        id,
        user_id,
        idempotency_key,
        operation_type,
        target_table,
        target_id,
        request_hash,
        result_status,
        response,
        error_code
      )
      values (
        p_operation_id,
        v_user_id,
        p_idempotency_key,
        'load.upsert',
        'loads',
        v_target_id,
        v_request_hash,
        'rejected',
        v_response,
        'stale_server_record'
      );

      return v_response;
    end if;

    if not app_private.is_load_status_transition_allowed(v_existing_load.status, v_status) then
      v_response := jsonb_build_object(
        'operation_id', p_operation_id,
        'idempotency_key', p_idempotency_key,
        'operation_type', 'load.upsert',
        'target_table', 'loads',
        'target_id', v_target_id,
        'result', 'rejected',
        'error_code', 'invalid_status_transition',
        'reconciliation', jsonb_build_object(
          'server_status', v_existing_load.status,
          'requested_status', v_status,
          'server_created_at', v_existing_load.created_at,
          'server_updated_at', v_existing_load.updated_at
        )
      );

      insert into public.sync_operations (
        id,
        user_id,
        idempotency_key,
        operation_type,
        target_table,
        target_id,
        request_hash,
        result_status,
        response,
        error_code
      )
      values (
        p_operation_id,
        v_user_id,
        p_idempotency_key,
        'load.upsert',
        'loads',
        v_target_id,
        v_request_hash,
        'rejected',
        v_response,
        'invalid_status_transition'
      );

      return v_response;
    end if;

    v_financial_changed :=
      v_existing_load.line_haul_rate is distinct from v_line_haul_rate
      or v_existing_load.fuel_surcharge is distinct from v_fuel_surcharge
      or v_existing_load.accessorial_revenue is distinct from v_accessorial_revenue
      or v_existing_load.loaded_miles is distinct from v_loaded_miles
      or v_existing_load.deadhead_miles is distinct from v_deadhead_miles
      or v_existing_load.estimated_tolls is distinct from v_estimated_tolls
      or v_existing_load.gross_revenue is distinct from v_gross_revenue
      or v_existing_load.total_operating_cost is distinct from v_total_operating_cost
      or v_existing_load.estimated_profit is distinct from v_estimated_profit
      or v_existing_load.profit_margin is distinct from v_profit_margin
      or v_existing_load.revenue_per_loaded_mile is distinct from v_revenue_per_loaded_mile
      or v_existing_load.revenue_per_total_mile is distinct from v_revenue_per_total_mile;

    if v_existing_load.status in ('invoiced', 'paid') and v_financial_changed then
      v_response := jsonb_build_object(
        'operation_id', p_operation_id,
        'idempotency_key', p_idempotency_key,
        'operation_type', 'load.upsert',
        'target_table', 'loads',
        'target_id', v_target_id,
        'result', 'rejected',
        'error_code', 'financial_conflict',
        'reconciliation', jsonb_build_object(
          'server_status', v_existing_load.status,
          'server_created_at', v_existing_load.created_at,
          'server_updated_at', v_existing_load.updated_at
        )
      );

      insert into public.sync_operations (
        id,
        user_id,
        idempotency_key,
        operation_type,
        target_table,
        target_id,
        request_hash,
        result_status,
        response,
        error_code
      )
      values (
        p_operation_id,
        v_user_id,
        p_idempotency_key,
        'load.upsert',
        'loads',
        v_target_id,
        v_request_hash,
        'rejected',
        v_response,
        'financial_conflict'
      );

      return v_response;
    end if;

    update public.loads
    set
      vehicle_id = v_vehicle_id,
      customer_id = v_customer_id,
      reference_number = v_reference_number,
      status = v_status,
      line_haul_rate = v_line_haul_rate,
      fuel_surcharge = v_fuel_surcharge,
      accessorial_revenue = v_accessorial_revenue,
      loaded_miles = v_loaded_miles,
      deadhead_miles = v_deadhead_miles,
      estimated_tolls = v_estimated_tolls,
      gross_revenue = v_gross_revenue,
      total_operating_cost = v_total_operating_cost,
      estimated_profit = v_estimated_profit,
      profit_margin = v_profit_margin,
      revenue_per_loaded_mile = v_revenue_per_loaded_mile,
      revenue_per_total_mile = v_revenue_per_total_mile,
      accepted_at = v_accepted_at,
      delivered_at = v_delivered_at
    where user_id = v_user_id
      and id = v_target_id
    returning * into v_saved_load;
  else
    if p_expected_server_updated_at is not null then
      v_response := jsonb_build_object(
        'operation_id', p_operation_id,
        'idempotency_key', p_idempotency_key,
        'operation_type', 'load.upsert',
        'target_table', 'loads',
        'target_id', v_target_id,
        'result', 'rejected',
        'error_code', 'missing_server_record',
        'reconciliation', jsonb_build_object(
          'server_created_at', null,
          'server_updated_at', null
        )
      );

      insert into public.sync_operations (
        id,
        user_id,
        idempotency_key,
        operation_type,
        target_table,
        target_id,
        request_hash,
        result_status,
        response,
        error_code
      )
      values (
        p_operation_id,
        v_user_id,
        p_idempotency_key,
        'load.upsert',
        'loads',
        v_target_id,
        v_request_hash,
        'rejected',
        v_response,
        'missing_server_record'
      );

      return v_response;
    end if;

    insert into public.loads (
      id,
      user_id,
      vehicle_id,
      customer_id,
      reference_number,
      status,
      line_haul_rate,
      fuel_surcharge,
      accessorial_revenue,
      loaded_miles,
      deadhead_miles,
      estimated_tolls,
      gross_revenue,
      total_operating_cost,
      estimated_profit,
      profit_margin,
      revenue_per_loaded_mile,
      revenue_per_total_mile,
      accepted_at,
      delivered_at
    )
    values (
      v_target_id,
      v_user_id,
      v_vehicle_id,
      v_customer_id,
      v_reference_number,
      v_status,
      v_line_haul_rate,
      v_fuel_surcharge,
      v_accessorial_revenue,
      v_loaded_miles,
      v_deadhead_miles,
      v_estimated_tolls,
      v_gross_revenue,
      v_total_operating_cost,
      v_estimated_profit,
      v_profit_margin,
      v_revenue_per_loaded_mile,
      v_revenue_per_total_mile,
      v_accepted_at,
      v_delivered_at
    )
    returning * into v_saved_load;
  end if;

  v_response := jsonb_build_object(
    'operation_id', p_operation_id,
    'idempotency_key', p_idempotency_key,
    'operation_type', 'load.upsert',
    'target_table', 'loads',
    'target_id', v_saved_load.id,
    'result', 'applied',
    'error_code', null,
    'reconciliation', jsonb_build_object(
      'server_created_at', v_saved_load.created_at,
      'server_updated_at', v_saved_load.updated_at,
      'server_status', v_saved_load.status
    )
  );

  insert into public.sync_operations (
    id,
    user_id,
    idempotency_key,
    operation_type,
    target_table,
    target_id,
    request_hash,
    result_status,
    response
  )
  values (
    p_operation_id,
    v_user_id,
    p_idempotency_key,
    'load.upsert',
    'loads',
    v_saved_load.id,
    v_request_hash,
    'applied',
    v_response
  );

  return v_response;
end;
$$;

revoke execute on function public.apply_load_sync_operation(uuid, text, jsonb, timestamp with time zone) from public, anon, authenticated;
grant execute on function public.apply_load_sync_operation(uuid, text, jsonb, timestamp with time zone) to authenticated;

comment on function public.apply_load_sync_operation(uuid, text, jsonb, timestamp with time zone) is
  'Idempotently inserts or updates one owned load snapshot and returns stable reconciliation metadata.';
